# syntax=docker/dockerfile:1

FROM python:3.13-slim-bookworm

RUN pip install --no-cache-dir --disable-pip-version-check \
        --index-url https://pypi.org/simple \
        "https://files.pythonhosted.org/packages/15/b4/e7121d99f2902b3e19a9e04d85124867f96bfe3dead7a2e945c7f628a3c1/mcp_server_tapd-8.0.81-py3-none-any.whl" \
    && useradd --system --uid 10002 --create-home --home-dir /app mcpuser

USER mcpuser
WORKDIR /app
EXPOSE 8000
ENTRYPOINT ["mcp-server-tapd"]
